### ISSUE TITLE
Input 自动高度设置不生效

### ISSUE THREAD

**Issue by Sunxinqiang** [ksc-fe/kpc#1029]
**CodeSandbox**
https://codesandbox.io/p/sandbox/eloquent-dawn-qrvfc2?file=%2Fsrc%2FApp.vue%3A8%2C16&workspaceId=337a5956-dc99-4b64-ae6b-cdee226c8cb3

**Description**
KPC: 3.4.2
当Input组件在Drawer内且被div包裹时，:rows="{ min: 20, max: 30 }"  属性设置失效

**Comment by Sunxinqiang** [comment]
期望不受外层影响

**Comment by Javey** [comment]
跟https://github.com/ksc-fe/kpc/issues/1026原因一样
