### ISSUE TITLE
支持通过 columnIndex 参数控制树形表格展开按钮的位置

### ISSUE THREAD

**Issue by junqiyue** [ksc-fe/kpc#1035]
描述:
目前，树形表格组件中的展开功能（箭头按钮）默认放置在第一列（即 columnIndex === 0）。然而，在某些使用场景下，允许开发者指定展开按钮所在的列会更加灵活。例如，将展开按钮放置在第三列可以在某些情况下提高表格的可读性和布局美观度。

预期行为:
建议为树形表格组件添加一个 columnIndex 或类似的配置项，允许开发者指定展开按钮显示在哪一列。

当前行为:
目前，树形表格展开按钮只能显示在第一列。这种限制减少了表格设计和布局的灵活性。

**Comment by Javey** [comment]
有相关设计的截图吗？

**Comment by junqiyue** [comment]
![image](https://github.com/user-attachments/assets/8d14fb58-217f-4cc1-9a05-520ad3ce790a)
@Javey

**Comment by warrior-bing** [comment]
Fix by v3.4.4
