### ISSUE TITLE
Tooltip设置了value不展示，实际鼠标悬浮上依然会展示

### ISSUE THREAD

**Issue by junqiyue** [ksc-fe/kpc#1039]
**CodeSandbox**
https://stackblitz.com/edit/vitejs-vite-pemmux?file=src%2FApp.vue

**Description**
Tooltip设置了value不展示，实际鼠标悬浮上依然会展示；场景：想根据变量控制Tooltip显隐

**Comment by warrior-bing** [comment]
value属性是控制默认是否是展示的，需求根据变量控制Tooltip显隐，可以使用disabled属性<Tooltip :disabled="!show" content="展示"> @junqiyue

**Comment by Javey** [comment]
![image](https://github.com/user-attachments/assets/2b86fdc3-2831-4054-9add-c1b49e6f7177)
添加always属性能够根据value控制显影

**Comment by junqiyue** [comment]
<img width="1281" alt="image" src="https://github.com/user-attachments/assets/9dcef6c9-bb2b-4319-8948-0e1101b1dbe9">
@Javey

**Comment by Javey** [comment]
@warrior-bing 冰哥，有时间看看这个bug

**Comment by Javey** [comment]
> value属性是控制默认是否是展示的，需求根据变量控制Tooltip显隐，可以使用disabled属性 @junqiyue

这个方案亲测有效
https://stackblitz.com/edit/vitejs-vite-qy3jzo?file=src%2FApp.vue

**Comment by junqiyue** [comment]
> > value属性是控制默认是否是展示的，需求根据变量控制Tooltip显隐，可以使用disabled属性 @junqiyue
> 
> 这个方案亲测有效 https://stackblitz.com/edit/vitejs-vite-qy3jzo?file=src%2FApp.vue

okk，加diabled是可以的，上次我也加了disabled没生效，估计页面没刷新，感谢两位大佬

**Comment by warrior-bing** [comment]
Fix by v3.4.4
