### ISSUE TITLE
Drawer中嵌套使用datetime日期时间选择时，选择日期，Drawer会消失

### ISSUE THREAD

**Issue by Javey** [ksc-fe/kpc#243]
因为点击日期时，日期组件会立即切换到时间选择面板，之前的dom会被移除，导致`Drawer`无法判断事件`e.target`是否包含在抽屉元素内，导致抽屉收起

> 其他元素如果点击后立即移除，也会存在此问题

**Comment by ws7she** [comment]
addEventListener改为在时间捕获时期进行
