### ISSUE TITLE
table组件点击删除会选中整行

### ISSUE THREAD

**Issue by leehave** [ksc-fe/kpc#249]
**描述Bug**
https://design.ksyun.com/components/table/ 导出表格时点击删除会选中行切换
列操作事件应该为单独事件

**Comment by Javey** [comment]
这是因为点击“删除”时事件冒泡给了`tr`，可以阻止该事件的冒泡即可
```vue
<!-- vue -->
<a @click.prevent="() => {}">删除</a>
```
```jsx
// react
<a onClick={(e) => {e.preventPropagation()}}>删除</a>
```

**Comment by leehave** [comment]
> 这是因为点击“删除”时事件冒泡给了`tr`，可以阻止该事件的冒泡即可
> 
> ```
> 
> <a @click.stop="() => {}">删除</a>
> ```
> 
> ```js-jsx
> // react
> <a onClick={(e) => {e.stopPropagation()}}>删除</a>
> ```

明了，多谢。
