### ISSUE TITLE
单选按钮radio 中间圆点没有居中(100%没有缩放)

### ISSUE THREAD

**Issue by 869123771** [ksc-fe/kpc#266]
![image](https://user-images.githubusercontent.com/23325269/57186881-57d5b680-6f19-11e9-87b2-13f75192d1f6.png)

**Comment by Javey** [comment]
默认主题是在根字体大小为`14px`的情况下设计的，不要覆盖了kpc中对`html`字体的定义，`html { font-size: 14px;}`

**Comment by Javey** [comment]
html应该定义成16px比较通用
