### ISSUE TITLE
FormItem rule url校验，hostname不支持IP地址

### ISSUE THREAD

**Issue by xuebinHe** [ksc-fe/kpc#282]
指定FormItem rule里url为true时，输入hostname为IP地址的url，返回失败。
建议增加支持hostname为IP的url校验。
http://www.cnblogs.com/01picker/p/4434197.html

**Comment by Javey** [comment]
该规则可以验证IP地址，但是会排除192.168.X.X | 192.254.X.X | 172.16.0.0 - 172.31.255.255 | 10.X.X.X | 172.X.X.X这类保留IP地址
这类IP地址做url的确不合法，所以目前的验证规则是合理的
