### ISSUE TITLE
【Datepicker】选择时间时，建议隐藏月份显示。

### ISSUE THREAD

**Issue by xuebinHe** [ksc-fe/kpc#285]
![屏幕快照 2019-05-17 下午4 44 13](https://user-images.githubusercontent.com/20663001/57992798-a7ef7400-7ae8-11e9-8b4f-92738886fcfa.png)
如图，Datepicker range为true，建议在选择时间时，隐藏掉红圈中月份提示

**Comment by Javey** [comment]
这个月份可以点击返回日期选择面板，可以加个返回按钮在前面强化一下这个交互，不建议删除

**Comment by xuebinHe** [comment]
红圈部分点击并没有跳转回日期选择面板

**Comment by Javey** [comment]
这种情况是tab切换返回日期选择面板，可以去掉
