### ISSUE TITLE
table组件支持缓存表头拖动后的宽度

### ISSUE THREAD

**Issue by x6doooo** [ksc-fe/kpc#292]
如题

**Comment by x6doooo** [comment]
辛苦大神支持一下哈

**Comment by Javey** [comment]
新增一个`headerWidthMap`的属性，并且当该属性变更时，触发相应的事件，以便外部来处理缓存逻辑，组件自身不太好做缓存

**Comment by Javey** [comment]
新增`storeWidth`属性，用来指定保存到`localStorage`中的`key`，通过该属性可以做到列宽信息持久化
