### ISSUE TITLE
建议增加分配数据相关类似穿梭框组件

### ISSUE THREAD

**Issue by PLAhui** [ksc-fe/kpc#314]
在开发中遇到类似于穿梭框的需求，是根据右侧框数据分配给指定左侧列表数据项，参考图片：
![image](https://user-images.githubusercontent.com/35413994/61039905-38b84100-a402-11e9-9eba-a4eb1c0b2a7c.png)

**Comment by Javey** [comment]
看了下，目前`Transfer`组件的确满足不了这种需求，后续会新增左右整个列表区域的扩展点，可以实现该需求

**Comment by PLAhui** [comment]
> 看了下，目前`Transfer`组件的确满足不了这种需求，后续会新增左右整个列表区域的扩展点，可以实现该需求
好的，我会关注该框架更新，

**Comment by Javey** [comment]
参见示例： https://codesandbox.io/s/u8hqv
