### ISSUE TITLE
属性使用了骆峰命名导至一些奇怪的问题

### ISSUE THREAD

**Issue by jktantan** [ksc-fe/kpc#420]
部分组件如：Table，的属性使用了骆峰命名，导致使用httpVueLoader动态加载的.vue文件的时，因为属性由驼峰命名变更为小写字母，导致组件加载异常。

**Comment by Javey** [comment]
如果是`.vue`文件，应该是支持驼峰命名的。
你贴一下相关代码看看

**Comment by jktantan** [comment]
我用的是“httpVueLoader"来加载VUE（非后台打包的方式）。
它里面有这么一段代码：
`load: function(componentURL) {

            return httpVueLoader.httpRequest(componentURL)
                .then(function(responseText) {

                    this.baseURI = componentURL.substr(0, componentURL.lastIndexOf('/')+1);
                    var doc = document.implementation.createHTMLDocument('');

                    // IE requires the <base> to come with <style>
                    doc.body.innerHTML = (this.baseURI ? '<base href="'+this.baseURI+'">' : '') + responseText;

                    for ( var it = doc.body.firstChild; it; it = it.nextSibling ) {

                        switch ( it.nodeName ) {
                            case 'TEMPLATE':
                                this.template = new TemplateContext(this, it);
                                break;
                            case 'SCRIPT':
                                this.script = new ScriptContext(this, it);
                                break;
                            case 'STYLE':
                                this.styles.push(new StyleContext(this, it));
                                break;
                        }
                    }

                    return this;
                }.bind(this));
        },`

 通过axios获取后VUE文件后，它会把这个VUE文件放到document里面来解析。。。这样。就会把所有驼峰变成小写了。。。。

**Comment by Javey** [comment]
你这种用法比较新颖，我研究研究

**Comment by jktantan** [comment]
> 你这种用法比较新颖，我研究研究

其实也不算新了，因为angularjs有个templateURL这玩意或者暂未使用完整的前端开发的话，会有这种需求。自己写个html解析器代价有点高，使用浏览器的又会把HTML的东西全变成小写，头痛。
另外，这个是httpVueLoader的github地址：

https://github.com/FranckFreiburger/http-vue-loader

**Comment by Javey** [comment]
这的确是个bug，我修复一下

**Comment by Javey** [comment]
@jktantan v1.3.4修复了该问题，你可以试试

**Comment by jktantan** [comment]
@Javey 没问题了，非常感谢。
