### ISSUE TITLE
关于Select自定义显示内容以及下拉树的问题

### ISSUE THREAD

**Issue by jktantan** [ksc-fe/kpc#423]
1. 发现KPC还未有下拉树的插件
2. 在没有下拉树插件的情况，想使用Select的自定义显示的方法自己组装个下拉树出来，但发现所谓的自定义显示其实只是Option的自定义显示，而不是整个下拉框的自定义显示，所以最后想实现下拉树功能，得自己写完整的写个组件出来。

建议：
1. 能有下拉树的功能
2. 在未有下拉树功能的情况下，能否实现下拉框的自定义显示，而不单单是Option的自定义显示？

**Comment by Javey** [comment]
是否可以用级联选择`Cascader`代替呢？结合`format`和`changeOnSelect`

**Comment by jktantan** [comment]
> 是否可以用级联选择`Cascader`代替呢？结合`format`和`changeOnSelect`

不可以，一般来说，政府方面的展现都会有“下拉树”的需求，如显示：部门或人员选择的情况，就会强制要使用下拉树的样式进行单选、多选、只选叶、可选枝等需求。

**Comment by Javey** [comment]
好的，可以安排上
