### ISSUE TITLE
VUE使用Dropdown报错

### ISSUE THREAD

**Issue by jktantan** [ksc-fe/kpc#424]
```
<KDropdown>
                    <KButton type="primary">
                        hover <KIcon class="ion-ios-arrow-down" />
                    </KButton>
                    <KDropdownMenu>
                        <KDropdownItem>item 1</KDropdownItem>
                        <KDropdownItem>item 2</KDropdownItem>
                        <KDropdownItem>item 3</KDropdownItem>
                    </KDropdownMenu>
</KDropdown>
```

复制于样例 ，运行的时间报这个错误：

> vue.min.js:6 TypeError: Cannot create property 'props' on string ' '
>     at Wrapper (kpc.vue.js:3138)
>     at render (kpc.vue.js:1011)
>     at vue.min.js:6
>     at Lt (vue.min.js:6)
>     at vue.min.js:6
>     at Pt (vue.min.js:6)
>     at wn.t._c (vue.min.js:6)
>     at wn.eval (eval at Ya (vue.min.js:6), <anonymous>:3:814)
>     at wn.e._render (vue.min.js:6)
>     at wn.r (vue.min.js:6)

**Comment by Javey** [comment]
需要配置`vue-loader`编译时去掉空格
https://vue-loader.vuejs.org/zh/options.html#compiler
`{ preserveWhitespace: false }`

**Comment by jktantan** [comment]
> 需要配置`vue-loader`编译时去掉空格
> https://vue-loader.vuejs.org/zh/options.html#compiler
> `{ preserveWhitespace: false }`

这样的话，应该就是打全量包的配置有问题，我是从CDN下的全量包出的问题，然后自己下原码默认打包流程也是这样。
