### ISSUE TITLE
Tree组件缺少checkbox点击事件，菜单展开收缩事件

### ISSUE THREAD

**Issue by jktantan** [ksc-fe/kpc#426]
tree组件有node的点击事件。但缺少了checkbox的点击事件，菜单的展开和收缩事情

**Comment by Javey** [comment]
KPC有一种事件，属于全局的，没有在单独的组件文档中提及，那就是[默认事件](https://design.ksyun.com/docs/event/)
![image](https://user-images.githubusercontent.com/5697987/72230997-d976fb80-35f3-11ea-9fb5-85ede6c40cf7.png)
`Checkbox`点击，菜单的展开和收缩，对应的属性如上所示，他们变化后会分别触发`$change:checkedKeys`和`$change:expandedKeys`事件，不知是否可以满足你的需求

ps：考虑到你使用的dom模板，事件名要由驼峰变为连字符形式`@$change:checked-keys="xxx"`

**Comment by jktantan** [comment]
> KPC有一种事件，属于全局的，没有在单独的组件文档中提及，那就是[默认事件](https://design.ksyun.com/docs/event/)
> ![image](https://user-images.githubusercontent.com/5697987/72230997-d976fb80-35f3-11ea-9fb5-85ede6c40cf7.png)
> `Checkbox`点击，菜单的展开和收缩，对应的属性如上所示，他们变化后会分别触发`$change:checkedKeys`和`$change:expandedKeys`事件，不知是否可以满足你的需求
> 
> ps：考虑到你使用的dom模板，事件名要由驼峰变为连字符形式`@$change:checked-keys="xxx"`

恩，这样应该可以，我先去试一下。

**Comment by jktantan** [comment]
没问题了，这样可以使用。
