### ISSUE TITLE
Radio 组件当后台返回的数据为整型时，无法匹配选中

### ISSUE THREAD

**Issue by zhuSilence** [ksc-fe/kpc#452]
看官方文档是采用===方式决定是否选中，但是经常会有很多状态类型的数据，这种在后台定义是整型的，到前端无法选中。只能修改后端数据类型，是否可以考虑不采用恒等呢？

**Comment by Javey** [comment]
注意Vue下`trueValue="1"`和`:trueValue="1"`的区别，前者是字符串，后者是整型
