### ISSUE TITLE
React +Ts 环境下组件报错

### ISSUE THREAD

**Issue by yancekang** [ksc-fe/kpc#562]
**CodeSandbox**

Warning: Button: type specification of prop `name` is invalid; the type checker function must return `null` or an `Error` but returned a string. You may have forgotten to pass an argument to the type checker creator (arrayOf, instanceOf, objectOf, oneOf, oneOfType, and shape all require an argument).

https://codesandbox.io/s/strange-heyrovsky-hiyuu?file=/src/App.tsx

**Description**

**Comment by Javey** [comment]
将`import * as React from "react";`改为`import React from "react";`即可

kpc-react会修改`React.createElement`函数，如果是第一种引用方式，`React`应该会被`freeze`，不能修改
