### ISSUE TITLE
引入一个组件会报下面的错误

### ISSUE THREAD

**Issue by yancekang** [ksc-fe/kpc#564]
代码片段： https://codesandbox.io/s/hidden-architecture-xvdkw

Warning: Button: type specification of prop `type` is invalid; the type checker function must return `null` or an `Error` but returned a string. You may have forgotten to pass an argument to the type checker creator (arrayOf, instanceOf, objectOf, oneOf, oneOfType, and shape all require an argument).

Warning: Button: type specification of prop `size` is invalid; the type checker function must return `null` or an `Error` but returned a string. You may have forgotten to pass an argument to the type checker creator (arrayOf, instanceOf, objectOf, oneOf, oneOfType, and shape all require an argument).
...

**Comment by Javey** [comment]
#562 和这个问题一样，我记得你提过，需要将React的引入方式改变一下
```js
import React from 'react';
```

**Comment by yancekang** [comment]
好奇怪啊，本地建的项目就是一直这个错误引入方式也是

`import React from 'react';`

codesandbox 上就正常

**Comment by Javey** [comment]
> 好奇怪啊本地项目就是一直这个错误引入方式也是, 可以在这个里面试试 https://codesandbox.io/s/hidden-architecture-xvdkw
> 
> `import React from 'react';`

是说采用`import React from 'react';`的方式也会报错吗？

**Comment by yancekang** [comment]
> > 好奇怪啊本地项目就是一直这个错误引入方式也是, 可以在这个里面试试 https://codesandbox.io/s/hidden-architecture-xvdkw
> > `import React from 'react';`
> 
> 是说采用`import React from 'react';`的方式也会报错吗？

是的，也有可能是项目配置问题吧

**Comment by Javey** [comment]
不知道是否使用的React@17，17的支持正在开发中，如果是的话，降级成16试试

**Comment by Javey** [comment]
可能和这个相关
https://zh-hans.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
