### ISSUE TITLE
table-column的invisible属性是不是没用

### ISSUE THREAD

**Issue by liubobuzhidao** [ksc-fe/kpc#674]
[源码](https://github.com/ksc-fe/kpc/blob/master/components/table/column.js)里面的这个属性是不是没啥用？如果我想动态隐藏header的话 该如何操作？

**Comment by Javey** [comment]
这个是内部在做列固定的时候用的
你隐藏header只能通过css `display: none`隐藏

**Comment by liubobuzhidao** [comment]
header虽然隐藏了 但对应的列还在  另外当table两侧有固定列时 在v2.0里没有了阴影效果
![image](https://user-images.githubusercontent.com/15080847/135054942-c48fde48-2e72-4b5d-854b-c32709e1dcd6.png)

**Comment by Javey** [comment]
隐藏列还是要通过css，给`TableColumn`一个class，然后`display: none;`

ps: 金山云同事？
