### ISSUE TITLE
Dialog静态方法（Dialog['confrim']）点击报错 uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'style')   

### ISSUE THREAD

**Issue by lemonzoey** [ksc-fe/kpc#816]
**CodeSandbox**
<Button @click='showDialog'>点击展示静态方法</Button>
showDialog(){
      Dialog['confirm']({
          title: '请确认',
          content:`xxxx`,
      }).then(() => {
        // 确认
      }, () => {
        // 取消
      });
    },

**Description**
caught (in promise) TypeError: Cannot read properties of undefined (reading 'style')
![image](https://user-images.githubusercontent.com/25550414/233386105-15aa678d-996c-489e-860b-46eecce11a35.png)
![image](https://user-images.githubusercontent.com/25550414/233386807-c386212f-67c9-4390-b2c2-1250ef349ec8.png)

**Comment by Javey** [comment]
用的1.6.1吧？应该是1.6.1引入的问题，可以先回退到1.6.0
下个版本修复

**Comment by Javey** [comment]
v1.6.2已修复
