### ISSUE TITLE
TextArea 组件增加拉伸的最大高度，禁止横向拉伸

### ISSUE THREAD

**Issue by jiayongchang** [ksc-fe/kpc#829]
1. 组件增加一个属性可以进行设置，类似最大行数和最小行数的参数
![image](https://github.com/ksc-fe/kpc/assets/67669980/8c36c599-911e-4360-9f57-4c76ee617690)
2. 横向拉伸可能会出现异常，且意义不大，希望禁掉。

**Comment by Javey** [comment]
-
