### ISSUE TITLE
是否有考虑更新文档中的实例代码，目前没有vue3和react hooks的代码

### ISSUE THREAD

**Issue by qinfeng0214** [ksc-fe/kpc#841]
react class写法现在用的非常少了

**Comment by Javey** [comment]
暂时没有考虑，因为这里仅仅只做组件功能的展示，并不是Vue和React的写法参考。
另外，这些代码其实都是通过一套模板，自动生成的，如果要自动生成hooks代码，成本还挺大。由于是自动生成的，所以并不是框架最佳写法，非常不具备参考性。

**Comment by qinfeng0214** [comment]
> 暂时没有考虑，因为这里仅仅只做组件功能的展示，并不是Vue和React的写法参考。 另外，这些代码其实都是通过一套模板，自动生成的，如果要自动生成hooks代码，成本还挺大。由于是自动生成的，所以并不是框架最佳写法，非常不具备参考性。

想问一下kpc v1.3.5支持ie9/ie10浏览器吗

**Comment by Javey** [comment]
支持
