### ISSUE TITLE
king-design/vue v2.0.11,Dialog组件设置:hideFooter="true"不生效

### ISSUE THREAD

**Issue by qinfeng0214** [ksc-fe/kpc#859]
**CodeSandbox**

<Dialog v-model="visible" :width="300" :hideFooter="true">
</Dialog>
**Description**

<Dialog v-model="visible" :width="300" :hideFooter="true">
</Dialog>
不能隐藏footer

**Comment by Javey** [comment]
hideFooter是静态方法的属性，Dialog本身不支持，如果需要隐藏footer，可以这么做
```vue
<Dialog v-model="show1" title="No Footer">
    <template v-slot:footer-wrapper>
        <div></div>
    </template>
</Dialog>
```
