### ISSUE TITLE
v2#Cascader#bug

### ISSUE THREAD

**Issue by kikcmime** [ksc-fe/kpc#953]
**CodeSandbox**
![image](https://github.com/ksc-fe/kpc/assets/90042724/befb9a07-4842-43ed-b922-9f10f3f457ec)

**Description**
当Cascader第一级数据过多时（我的数据有450条），点开里面第三级时第三级的弹窗会飞到页面的左上角，来回点击第一级会变好，但是第一次渲染就会飘飞（详细请看协作私聊）

**Comment by Javey** [comment]
https://github.com/ksc-fe/kpc/issues/894
