### ISSUE TITLE
使用了一段时间的king design v3，感觉组件的聚焦动画很奇怪，闪好几下，有办法全局禁用了吗

### ISSUE THREAD

**Issue by qinfeng0214** [ksc-fe/kpc#984]
看着不是很舒服，这是我的主观感受，放佛组件要坏了的感觉

**Comment by Javey** [comment]
是Button和Input等组件点击的水波纹动效吗？

**Comment by qinfeng0214** [comment]
> 是Button和Input等组件点击的水波纹动效吗？

对的，感觉闪烁的太快了，视觉上感觉不是很舒服

**Comment by Javey** [comment]
@warrior-bing 跟进下这个问题
通过`ConfigProvider`新增配置项解决，名称就叫`disableWave`，默认为`false`
