### ISSUE TITLE
希望组件库可以把dayjs暴露出来，允许从组件库导出dayjs

### ISSUE THREAD

**Issue by qinfeng0214** [ksc-fe/kpc#987]
**Is your feature request related to a problem? Please describe.**
项目中其他地方也需要使用dayjs，需要安装dayjs，打包的时候不确定是不是会打包两份dayjs
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Javey** [comment]
只要以来的版本一致，就不会打包两份
`"dayjs": "^1.10.7"`

**Comment by qinfeng0214** [comment]
> 只要依赖的版本一致，就不会打包两份 `"dayjs": "^1.10.7"`

组件库可以暴露出来dayjs吗？这样就能保证不会打包2份dayjs，目前我使用的是dayjs v1.11.10。
像下面这样：
import { dayjs } from '@king-design/vue'

**Comment by Javey** [comment]
@warrior-bing 在`components/datepicker/index.ts`添加`export { dayjs };`，把dayjs暴露出来
