### ISSUE TITLE
table组件添加包含隐藏列的时候，宽度计算错误

### ISSUE THREAD

**Issue by zhanghaikuo001** [ksc-fe/kpc#996]
**CodeSandbox**
<table>
<thead>
<tr>
<th></th>
<th calss="hideColumn">隐藏当前列</th>
<th calss="hideColumn">隐藏当前列</th>
<th></th>
<th></th>
...
</tr>
<thead>
<tbody>
<tr>
<td class="k-table-empty" colspan="10">

**Description**
k-table-empty的 colspan没有正确计算隐藏列的数量

**Comment by Javey** [comment]
需要给`TableColumn`添加`hidden`属性，用于隐藏列，这样当无数据时，能够计算出实际展示的列数`colspan`

**Comment by warrior-bing** [comment]
fix by [pull1003](https://github.com/ksc-fe/kpc/pull/1003)
