### ISSUE TITLE
Switch开关放到FormItem的label里时会失效，点击无法操作开闭

### ISSUE THREAD

**Issue by AmazingBubble** [ksc-fe/kpc#997]
**CodeSandbox**
<FormItem 
					:value="data.callback"
				>
					<template slot="label">
						<span class="margin-r-8">{{ _$('设置回调') }}</span>
						**<KSwitch v-model="openCallback" size='small' />**
					</template>
					<Input v-if="openCallback" class="margin-t-8" width="400" v-model="data.callback" :placeholder="_$('请输入回调地址，以http[s]://开头')"></Input>
				</FormItem>

**Description**

**Comment by Javey** [comment]
贴下代码看看

**Comment by AmazingBubble** [comment]
<FormItem 
	:value="data.callback"
>
	<template slot="label">
		<span class="margin-r-8">{{ _$('设置回调') }}</span>
		<KSwitch v-model="openCallback" size='small' />
	</template>
	<Input v-if="openCallback" class="margin-t-8" width="400" v-model="data.callback" :placeholder="_$('请输入回调地址，以http[s]://开头')"></Input>
</FormItem>

**Comment by warrior-bing** [comment]
@AmazingBubble label标签默认行为影响，如下阻止默认行为即可
<FormItem
	:value="data.callback"
>
	<template slot="label">
	        <div @click.prevent>
		        <span class="margin-r-8">{{ _$('设置回调') }}</span>
		       <KSwitch v-model="openCallback" size='small' />
		</div>
	</template>
	...
</FormItem>
